sudo: required

language: cpp

cache: apt

compiler:
 - gcc
 - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install: sudo apt-get install libboost-system-dev libboost-thread-dev libglu1-mesa-dev libwxgtk3.0-dev libarchive-dev

before_script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..

script: make
